#!/bin/bash
# ==============================================================================
# Sync API Keys from Shell Environment to .env file
# ==============================================================================
# This script is SAFE TO COMMIT - it contains no actual keys.
# It reads from your shell environment and writes to .env (which is gitignored).
#
# Usage:
#   ./scripts/sync_api_keys.sh           # Sync keys to .env
#   ./scripts/sync_api_keys.sh --check   # Just verify keys are set
#
# Reference: Platform Documentation/Platform-Wide/Reference/API_KEY_MANAGEMENT.md
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

# Required API keys for LLM providers
REQUIRED_KEYS=(
    "OPENAI_API_KEY"
    "ANTHROPIC_API_KEY"
    "OPENROUTER_API_KEY"
    "DEEPSEEK_API_KEY"
    "GEMINI_API_KEY"
)

# Check mode - just verify keys exist
if [[ "$1" == "--check" ]]; then
    echo "🔍 Checking API keys in shell environment..."
    missing=0
    for key in "${REQUIRED_KEYS[@]}"; do
        value="${!key}"
        if [[ -n "$value" ]]; then
            echo "  ✓ $key is set"
        else
            echo "  ✗ $key is NOT set"
            missing=$((missing + 1))
        fi
    done
    
    if [[ $missing -gt 0 ]]; then
        echo ""
        echo "⚠️  $missing key(s) missing. Add them to ~/.zshrc:"
        echo "   export MISSING_KEY=\"your-key-here\""
        exit 1
    else
        echo ""
        echo "✅ All API keys are set in shell environment"
        exit 0
    fi
fi

# Sync mode - write keys to .env
echo "🔄 Syncing API keys from shell environment to .env..."

# Check all keys are set before writing
missing_keys=()
for key in "${REQUIRED_KEYS[@]}"; do
    value="${!key}"
    if [[ -z "$value" ]]; then
        missing_keys+=("$key")
    fi
done

if [[ ${#missing_keys[@]} -gt 0 ]]; then
    echo "❌ Cannot sync - missing keys in shell environment:"
    for key in "${missing_keys[@]}"; do
        echo "   - $key"
    done
    echo ""
    echo "Add missing keys to ~/.zshrc and run: source ~/.zshrc"
    exit 1
fi

# Write .env file (preserving any non-API-key settings)
# First, read existing non-API-key lines
existing_config=""
if [[ -f "$ENV_FILE" ]]; then
    existing_config=$(grep -v "API_KEY=" "$ENV_FILE" 2>/dev/null || true)
fi

# Write new .env
cat > "$ENV_FILE" << EOF
# ==============================================================================
# LLM Gateway API Keys - AUTO-GENERATED by sync_api_keys.sh
# DO NOT COMMIT THIS FILE (it's in .gitignore)
# Last synced: $(date '+%Y-%m-%d %H:%M:%S')
# ==============================================================================

# LLM Provider API Keys (synced from shell environment)
OPENAI_API_KEY=$OPENAI_API_KEY
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
OPENROUTER_API_KEY=$OPENROUTER_API_KEY
DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY
GEMINI_API_KEY=$GEMINI_API_KEY

EOF

# Append existing non-API-key config
if [[ -n "$existing_config" ]]; then
    echo "# Preserved settings from previous .env" >> "$ENV_FILE"
    echo "$existing_config" >> "$ENV_FILE"
fi

echo "✅ API keys synced to $ENV_FILE"
echo ""
echo "Keys written:"
for key in "${REQUIRED_KEYS[@]}"; do
    echo "  ✓ $key"
done
echo ""
echo "Next: Restart the gateway to pick up the new keys:"
echo "  docker restart platform-llm-gateway"
